class_names = [
    'Apple___Apple_scab', 'Apple___Black_rot', 'Apple___Cedar_apple_rust', 'Apple___healthy',
    'Blueberry___healthy', 'Cherry_(including_sour)___Powdery_mildew', 'Cherry_(including_sour)___healthy',
    'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot', 'Corn_(maize)___Common_rust_',
    'Corn_(maize)___Northern_Leaf_Blight', 'Corn_(maize)___healthy', 'Grape___Black_rot',
    'Grape___Esca_(Black_Measles)', 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)', 'Grape___healthy',
    'Orange___Haunglongbing_(Citrus_greening)', 'Peach___Bacterial_spot', 'Peach___healthy',
    'Pepper,_bell___Bacterial_spot', 'Pepper,_bell___healthy', 'Potato___Early_blight',
    'Potato___Late_blight', 'Potato___healthy', 'Raspberry___healthy', 'Soybean___healthy',
    'Squash___Powdery_mildew', 'Strawberry___Leaf_scorch', 'Strawberry___healthy',
    'Tomato___Bacterial_spot', 'Tomato___Early_blight', 'Tomato___Late_blight', 'Tomato___Leaf_Mold',
    'Tomato___Septoria_leaf_spot', 'Tomato___Spider_mites Two-spotted_spider_mite', 'Tomato___Target_Spot',
    'Tomato___Tomato_Yellow_Leaf_Curl_Virus', 'Tomato___Tomato_mosaic_virus', 'Tomato___healthy'
]

disease_cures = {
    "Apple___Apple_scab": "Apply fungicides like Captan, Myclobutanil, or Mancozeb early to prevent spores. Prune infected leaves and maintain good airflow.",
    "Apple___Black_rot": "Remove infected branches and fruits. Apply copper-based fungicides and disinfect pruning tools regularly.",
    "Apple___Cedar_apple_rust": "Use fungicides containing Myclobutanil. Remove nearby cedar trees or prune galls from them in winter.",
    "Apple___healthy": "No treatment needed. Ensure proper pruning, watering, and fertilization.",
    "Blueberry___healthy": "No treatment needed. Maintain good soil drainage and proper pH levels.",
    "Cherry_(including_sour)___Powdery_mildew": "Apply sulfur-based fungicides. Prune infected areas and avoid overhead watering.",
    "Cherry_(including_sour)___healthy": "No treatment needed. Ensure proper pruning and fertilization.",
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot": "Apply fungicides like Azoxystrobin. Rotate crops and remove infected residues.",
    "Corn_(maize)___Common_rust_": "Plant resistant varieties. Apply Mancozeb or Copper-based fungicides.",
    "Corn_(maize)___Northern_Leaf_Blight": "Use resistant hybrids. Apply Mancozeb or Strobilurin-based fungicides.",
    "Corn_(maize)___healthy": "No treatment needed. Ensure balanced fertilization and irrigation.",
    "Grape___Black_rot": "Prune infected leaves and apply Mancozeb or Captan fungicides. Maintain good vineyard hygiene.",
    "Grape___Esca_(Black_Measles)": "Remove infected vine wood and apply Trichoderma-based biological fungicides.",
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": "Apply copper-based fungicides and prune affected leaves.",
    "Grape___healthy": "No treatment needed. Ensure proper pruning and irrigation.",
    "Orange___Haunglongbing_(Citrus_greening)": "No cure available. Control psyllid populations and remove infected trees.",
    "Peach___Bacterial_spot": "Apply copper-based sprays in early spring. Prune infected branches and avoid overhead watering.",
    "Peach___healthy": "No treatment needed. Maintain proper pruning and irrigation.",
    "Pepper,_bell___Bacterial_spot": "Use copper-based sprays. Avoid overhead watering and remove infected plants.",
    "Pepper,_bell___healthy": "No treatment needed. Ensure good soil drainage and sunlight.",
    "Potato___Early_blight": "Apply Chlorothalonil or Copper-based fungicides. Rotate crops and mulch to prevent soil splash.",
    "Potato___Late_blight": "Use Copper-based fungicides or Mancozeb. Avoid overhead irrigation and remove infected plants.",
    "Potato___healthy": "No treatment needed. Maintain healthy soil and proper watering.",
    "Raspberry___healthy": "No treatment needed. Ensure good air circulation and remove old canes.",
    "Soybean___healthy": "No treatment needed. Practice crop rotation and balanced fertilization.",
    "Squash___Powdery_mildew": "Apply sulfur-based fungicides or neem oil. Increase airflow and avoid wetting leaves.",
    "Strawberry___Leaf_scorch": "Use copper-based fungicides. Prune infected leaves and ensure good air circulation.",
    "Strawberry___healthy": "No treatment needed. Maintain proper fertilization and irrigation.",
    "Tomato___Bacterial_spot": "Use copper-based fungicides. Avoid overhead watering and remove infected plants.",
    "Tomato___Early_blight": "Apply Chlorothalonil or Mancozeb. Rotate crops and mulch to prevent soil splash.",
    "Tomato___Late_blight": "Use Copper-based fungicides. Remove infected plants and avoid excessive moisture.",
    "Tomato___Leaf_Mold": "Improve ventilation and apply sulfur-based fungicides.",
    "Tomato___Septoria_leaf_spot": "Apply fungicides like Chlorothalonil and practice crop rotation.",
    "Tomato___Spider_mites Two-spotted_spider_mite": "Use insecticidal soap or neem oil to control mite populations.",
    "Tomato___Target_Spot": "Apply copper-based fungicides and maintain good airflow around plants.",
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": "Remove infected plants. Control whiteflies with insecticidal soap or neem oil.",
    "Tomato___Tomato_mosaic_virus": "Remove infected plants and disinfect tools regularly.",
    "Tomato___healthy": "No treatment needed. Ensure balanced fertilization and irrigation."
}

